language: python
python:
  - 2.7
before_install:
  - time pip install -r requirements/testing.txt
  #- pylint hotsparser
  #- flake8 hotsparser

script:
  - pep8 replaylib

sudo: false

notifications:
  email:
    on_success: never
    on_failure: never